### ISSUE TITLE
Problem building with newest unstable nixpkgs

### ISSUE THREAD

**Issue by athas** [nixos-rocm/nixos-rocm#23]
So, first up, Linux 5.2 is no longer part of Nixpkgs, so it has to be bumped to 5.3 (at the oldest).  After that, I still get compile errors that I cannot figure out:

```
In file included from /build/ROCm-OpenCL-Runtime-roc-2.9.0-src/runtime/device/rocm/rocglinterop.cpp:10:
/build/ROCm-OpenCL-Runtime-roc-2.9.0-src/runtime/device/rocm/rocglinterop.hpp:9:10: fatal error: 'GL/glx.h' file not found
#include <GL/glx.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [runtime/device/rocm/CMakeFiles/oclrocm.dir/build.make:167: runtime/device/rocm/CMakeFiles/oclrocm.dir/rocglinterop.cpp.o] Error 1
```

**Comment by acowley** [comment]
Thank you for the note about bumping the kernel version in the README!

Did you get that error when doing a `nixos-rebuild` or building a particular package?

For me, the `dev` output of the `mesa_noglu` derivation has an `include` directory that contains `GL/glx.h`. Since `mesa_noglu` is listed among the `buildInputs` of `rocm-opencl-runtime`, that `include` directory should be passed to the C/C++ compiler. Can you check that the `dev` output of `mesa_noglu` has the expected headers on your machine?

**Comment by athas** [comment]
This is with a `nixos-rebuild --upgrade`.  I'll check `mesa_noglu`.

**Comment by athas** [comment]
Is this how I'm supposed to check?

```
$ nix-build '<nixpkgs>' -A mesa_noglu.dev
/nix/store/86av19fvp3v4aapqc919k4p68qp3chz8-mesa-19.2.1-dev
```

It also seems like `/nix/store/86av19fvp3v4aapqc919k4p68qp3chz8-mesa-19.2.1-dev/include/GL/glx.h` exists, but I'm not Nix-savvy to know whether this is actually the one it looks for.

**Comment by athas** [comment]
I'm actually quite confused about what's even going on now. `nix-build '<nixpkgs>' -A rocm-opencl-runtime` works fine, but is clearly building something else (with a different hash) than what is being built with `nixos-rebuild`.

**Comment by athas** [comment]
`evils` on #nixos mentioned that he had to add a libGLU dependency to rocm-opencl-runtime: https://hastebin.com/ibepufecor.diff

This also makes it build for me.  (Haven't checked functionality yet.)

**Comment by athas** [comment]
There seems to be an incompatibility with the 5.3 (and newer kernels).  For 5.4, I needed the following extra configuration ([which I took from you](https://github.com/RadeonOpenCompute/ROCm/issues/906)):

```
 boot.kernelPatches = [ {
    name = "make-rocm-work";
    patch = null;
    extraConfig = ''
                ZONE_DEVICE y
                HMM_MIRROR y
                DRM_AMDGPU_USERPTR y
                '';
  } ];
```

**Comment by acowley** [comment]
Ah, yes, that was painfully gained esoterica on my part. I’ve gotten an AMDGPU patch into the NixOS kernel config before, but I’m so wary of doing that without being mostly certain it’s the right thing since it rebuilds a *lot* on hydra, and potentially affects all users. The problem I had here was that the hints I found around these kernel options also suggested it was a temporary state of affairs, so I thought I should learn more, maybe AMDGPU changes to not need them, and it would be good to hear if anybody else needed these options. 

None of those happened until now 😜. If we need those options on 5.4 and 5.3, then I think it’s worth us following up on getting them into the NixOS default kernel config. We should find some supporting links describing things to make the case for that PR.

I don’t know what’s going on with that libGLU dependency. If `nix-build` and `nixos-rebuild` are behaving differently from each other for you, then my first guess would be that your user has a different `NIX_PATH` than root, or something along those lines. This can happen with `nix-channel` being the weird duck that it is.

**ETA:** actually `ZONE_DEVICE` and `DRM_AMDGPU_USERPTR` are both set in the default Ubuntu kernel configuration afaict, so I'm going to rebuild everything with those conditioned on the kernel being at least 5.3. Assuming that's all good, I will open a PR on nixpkgs.

**Comment by acowley** [comment]
I've opened the [PR](https://github.com/NixOS/nixpkgs/pull/75176).
