### ISSUE TITLE
[Feature Request] Add a Configuration Option to Broadly Specify Optimization Level

### ISSUE THREAD

**Issue by Wulfsta** [nixos-rocm/nixos-rocm#37]
As mentioned [here](https://github.com/nixos-rocm/nixos-rocm/issues/34#issuecomment-623209153), there is at least one derivation in this overlay that has flags for different levels of optimization. I was wondering if it would be appropriate to account for this by introducing a global configuration option to specify what flags should be used to build? I would advocate for this to make it more known to users that flags like this exist, and handle possible future additions with similar options.

**Comment by acowley** [comment]
Exposing this is the right thing to do. I've not pursued it because in my experience these values for tensile optimization are not all tested by upstream: different ones are broken at different times. Until upstream stabilizes and documents these things, us exposing the options to our users is just foisting the trouble of most of the flags usually being broken onto our users.

If we're at the point where we have two different ones building, then we should absolutely expose it. Maybe we're there now if we can get things working with `asm_lite` and `asm_full`. The `hip_lite` option failed to build for me yesterday.

**Comment by Wulfsta** [comment]
Closing this as I believe we should always be using `asm_full`.
