### ISSUE TITLE
Does not work as of now

### ISSUE THREAD

**Issue by vorot93** [nixos-rocm/nixos-rocm#4]
Looks like old releases get deleted from repo.radeon.com and this overlay has not been updated in a while.

**Comment by acowley** [comment]
My [fork](https://github.com/acowley/nixos-rocm) should work. The plan was to setup an organization under which to host this effort, but we haven’t done so yet.

**Comment by vorot93** [comment]
Thanks! Perhaps you should, since Google points to this repo. And I'd be happy to join the endeavour.

**Comment by pl-semiotics** [comment]
Oh, I'm sorry I missed that---I haven't been working on this much lately, due to a combination of other responsibilities & planning on making a major push (including setting up the org) when Linux 4.18 (or a usable RC) is released and a lot more ROCm targets are supported on the mainline kernel. In the meantime, @acowley, would you mind if I merged your changes into this repo quickly for the sake of discoverability?

**Comment by acowley** [comment]
I've opened a [PR](https://github.com/peter-sa/nixos-rocm/pull/5) to merge 1.8.0.

**Comment by acowley** [comment]
@vorot93 You may also want to take a look at the [other `ROCm`-related software](https://github.com/acowley/dotfiles/blob/master/rocm.nix) I've packaged.

**Comment by acowley** [comment]
@peter-sa would it be okay with you if I started the organization now with the three of us as the initial members?

**Comment by vorot93** [comment]
@acowley Could please create the organization now and add all of us there in the mean time?

@peter-sa Would you mind merging the [PR](https://github.com/peter-sa/nixos-rocm/pull/5) and moving the repo to the new org?

**Comment by pl-semiotics** [comment]
@vorot93 @acowley I'm really sorry for disappearing; a couple of unexpected real-life things came up! I will merge the PR & move the repo to an org now.

**Comment by peter-sa** [comment]
@acowley can you clarify what the vboxvideo-ttm patch is for?
