### ISSUE TITLE
Upgrade to 3.7.0

### ISSUE THREAD

**Issue by athas** [nixos-rocm/nixos-rocm#56]
AMD saw fit to unleash ROCm 3.7.0, and in particular they seem to have gotten around to supporting the Navi architecture!

**Comment by acowley** [comment]
I packaged parts of 3.7.0 [here](https://github.com/acowley/nixos-rocm/tree/3.7.x).

I didn't get to the higher level libraries yet, though. It currently has OpenCL and HIP.

**Comment by athas** [comment]
Well, the brave and true can get by with just OpenCL.  Thanks for that!

**Comment by Wulfsta** [comment]
Once this is through and the [TensorFlow 2.3.0 pull](https://github.com/NixOS/nixpkgs/pull/95824) is resolved, I will restart work on getting it building from source.

**Comment by athas** [comment]
For some reason AMD has already released ROCm 3.8.0, so I guess 3.7.0 can be skipped for nixos-rocm.

**Comment by acowley** [comment]
I don’t know how much I’ll update this repo moving forward as we now have a split between nixpkgs, this repo which we don’t have a maintainer for, and our personal forks which we can hold to a lower standard. Keeping things synced in three places is probably one too many.

I’ve been using 3.7 for a while now with success, and there’s a PR to update OpenCL in nixpkgs to 3.8, so I think there are multiple good options for the lower level pieces.

**Comment by athas** [comment]
I had not realised that ROCm had been added to Nixpkgs.  I agree that significantly lessens the need for this repository.  Is there in fact any need left at all?

**Comment by Wulfsta** [comment]
@athas High level libraries have not yet been included, there is some discussion [here](https://github.com/Wulfsta/nixos-rocm/commit/86cb16d9fa2a3fd5effd3bfcdcce149613d8a540#commitcomment-40754351).

**Comment by Wulfsta** [comment]
@acowley regarding your post, do you intend to keep updating your fork? If you have no intention of working on high level libraries I will (once 3.8 is out and I have time) fork whoever has the most up to date repository and start updating and writing tests for the dependencies for high level libraries with intent to incrementally move them into nixpkgs. I would very much like to have TensorFlow (and possibly PyTorch) with a ROCm backend available in nixpkgs in the future.

**Comment by acowley** [comment]
@Wulfsta I am still interested in the high level libraries, but on a daily basis I really only *need* `hip`, so it can be tricky for me to find time to work on the other things. If the other things worked more reliably I'd probably end up needing them, too, so I'm definitely interested in keeping things going.

**Comment by acowley** [comment]
My fork is updated to 3.8 with at least HIP.

Question for anyone who cares to answer: would it be more helpful to update this repo to 3.8 even though the higher level libraries have fallen behind? I've left it where it is because we had more things building in the past, but as the versions march on this falls further behind which doesn't seem great.

**Comment by Wulfsta** [comment]
I might start poking at this sometime today then, and see if I can work towards higher level libraries for 3.8. I think that keeping this repository up to date is useful to possibly attract more people to work on it (or at least let them know it's being worked on), since it is the top result when you serch "NixOS ROCm." Personally I will probably begin tracking your fork, but I definitely think there is merit to updating here as well.

**Comment by acowley** [comment]
This is a valuable discussion, but perhaps no longer an open Issue.

**Comment by danieldk** [comment]
> I might start poking at this sometime today then, and see if I can work towards higher level libraries for 3.8.

I'll extend the offer here ;). If someone is interested in maintaining higher level libraries in nixpkgs, feel free to ping me for reviews/merges.

(And apologies for replying in a closed issue!)

**Comment by Wulfsta** [comment]
@danieldk I actually have done some [work](https://github.com/Wulfsta/nixos-rocm/tree/3.8.x-tensorflow) on that, and while it's still 3.8.0 I could use another set of eyes. There is some ongoing commentary [here](https://github.com/acowley/nixos-rocm/pull/10), and I think the current issue is either in the TensorFlow or MIOpen builds. I am particularly suspicious of [this line](https://github.com/Wulfsta/nixos-rocm/blob/ebe1f5c3c7e43b410c8b18d6be3f139d537a624a/pkgs/development/libraries/tensorflow/2/default.nix#L120) since I don't have access to a machine with that file already on it and just took a guess at the information.
